[package]
name = "SystemMonitor"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
fltk = { version = "1", features = ["fltk-bundled"] }
fltk-theme = "0.7"
sysinfo = "0.39.6"

[target.'cfg(windows)'.dependencies]
winreg = "0.56"

[profile.release]
opt-level = 3
lto = true
strip = true

[build-dependencies]
embed-resource = "3.0.11"